name: outagamie_emergency_management_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.0.11 
  file_picker: ^5.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  postgres: ^3.2.0
  image: ^4.1.7
  bcrypt: ^1.1.3
  share_plus: ^7.2.2
  file_selector: ^1.0.3
  image_picker: ^1.0.8
  image_preview: ^1.0.7
  pdf: ^3.10.8
  printing: ^5.12.0
  open_file: ^3.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assests/
  