// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sA2ePkvcvpTycRCVZA4VhjlD-mwIzW8',
    appId: '1:186697892415:web:aa1d338a9559ef3aa7ee8a',
    messagingSenderId: '186697892415',
    projectId: 'outagamieemergencyapp',
    authDomain: 'outagamieemergencyapp.firebaseapp.com',
    databaseURL: 'https://outagamieemergencyapp-default-rtdb.firebaseio.com',
    storageBucket: 'outagamieemergencyapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4sA2ePkvcvpTycRCVZA4VhjlD-mwIzW8',
    appId: '1:186697892415:web:997adcef688def4aa7ee8a',
    messagingSenderId: '186697892415',
    projectId: 'outagamieemergencyapp',
    authDomain: 'outagamieemergencyapp.firebaseapp.com',
    databaseURL: 'https://outagamieemergencyapp-default-rtdb.firebaseio.com',
    storageBucket: 'outagamieemergencyapp.firebasestorage.app',
  );

}